### ISSUE TITLE
Module has no attribute

### ISSUE THREAD

**Issue by Ananthu2oo3** [kactlabs/error-archive#301]
Traceback (most recent call last):
  File "/home/deepak/tact/tactlabs_tasks/split_array.py", line 1, in <module>
    import numpy as np
  File "/home/deepak/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/deepak/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/core/__init__.py", line 71, in <module>
    from . import numerictypes as nt
  File "/home/deepak/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/core/numerictypes.py", line 594, in <module>
    _register_types()
  File "/home/deepak/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/core/numerictypes.py", line 589, in _register_types
    numbers.Integral.register(integer)
AttributeError: module 'numbers' has no attribute 'Integral'

**Comment by Ananthu2oo3** [comment]
There was a file named numbers.py in the folder which conflict with numpy numbers module and renaming the file fixed it.
